Fix naclports dosbox build for newlib.  The dosbox-specific getpwnam stub conflicts with the one in naclmounts.
Error message on bots was:

/mnt/data/b/build/slave/linux-pnacl_newlib-all/build/src/build_tools/../pepper_XX/toolchain/linux_x86_pnacl/newlib/bin/pnacl-clang++  -O3 -g   -O0 -o dosbox dosbox.o  cpu/libcpu.a debug/libdebug.a dos/libdos.a fpu/libfpu.a  hardware/libhardware.a gui/libgui.a ints/libints.a misc/libmisc.a shell/libshell.a hardware/serialport/libserial.a libs/gui_tk/libgui_tk.a ppapi/libppapi.a -Wl,--whole-archive       -lppapi       -lppapi_cpp       -lSDL       -lSDLmain       -Wl,--no-whole-archive       ppapi/libppapi.a       -lnacl-mounts -L/mnt/data/b/build/slave/linux-pnacl_newlib-all/build/src/build_tools/../pepper_XX/toolchain/linux_x86_pnacl/newlib/usr/lib       -lm       -lpng       -lz -L/mnt/data/b/build/slave/linux-pnacl_newlib-all/build/src/build_tools/../pepper_XX/toolchain/linux_x86_pnacl/newlib/usr/lib -lSDL -lpthread -lm -lpthread -lpng -lz -lnosys
/mnt/data/b/build/slave/linux-pnacl_newlib-all/build/src/pepper_XX/toolchain/linux_x86_pnacl/pkg/binutils/bin/arm-pc-nacl-ld.gold: error: /mnt/data/b/build/slave/linux-pnacl_newlib-all/build/src/build_tools/../pepper_XX/toolchain/linux_x86_pnacl/newlib/usr/lib/libnacl-mounts.a: multiple definition of 'getpwnam'
/mnt/data/b/build/slave/linux-pnacl_newlib-all/build/src/pepper_XX/toolchain/linux_x86_pnacl/pkg/binutils/bin/arm-pc-nacl-ld.gold: ppapi/libppapi.a: previous definition here


Also add it (and snes9x) to the list of things to build under the
buildbots, so that it's not just the pnacl bot building it,
and we can tell if it's a pnacl-only problem or not.

BUG= http://code.google.com/p/naclports/issues/detail?id=45
Review URL: https://chromiumcodereview.appspot.com/10407005

git-svn-id: http://naclports.googlecode.com/svn/trunk/src@592 7dad1e8b-422e-d2af-fbf5-8013b78bd812